### ISSUE TITLE
question 152 layer

### ISSUE THREAD

**Issue by peternara** [XiaozhiChen/resnet-generator#3]
i success 50 layer(~ing...).
but i make def file for 152 layer (based on resnet paper and your examples).
i have a next problem.

 -# number of layers
152
-# number of stages from conv2
4
-# definition of stages: conv #block learn_weights
conv 3 0
1 64
3 64
1 256
conv 8 1
1 128
3 128
1 512
conv 36 1
1 256
3 256
1 1024
conv 3 1
1 512
3 512
1 2048

but next error generate,,!

...
I0315 16:46:23.134991 31153 net.cpp:270] This network produces output loss_cls
I0315 16:46:23.134996 31153 net.cpp:270] This network produces output rpn_cls_loss
I0315 16:46:23.135004 31153 net.cpp:270] This network produces output rpn_loss_bbox
I0315 16:46:23.135278 31153 net.cpp:283] Network initialization done.
I0315 16:46:23.136476 31153 solver.cpp:60] Solver scaffolding done.
Loading pretrained model weights from data/imagenet_models/ResNet-152-model.caffemodel
 Check failed: target_blobs.size() == source_layer.blobs_size() (2 vs. 1) Incompatible number of blobs for layer conv1
**\* Check failure stack trace: ***
중지됨 (core dumped)

do you know this problem?  memory size problem ?? hmm
or you try???152 layers? Are you show  152 def (file) examples ??

**Comment by XiaozhiChen** [comment]
@peternara 
It's because the original [Resnet-152](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-152-deploy.prototxt) does not use bias term in conv1, while [Resnet-50](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt) includes the bias term. Therefore, you can add `bias_term: false` in the conv1 layer once you generate the prototxt.

Also, the naming conventions of [Resnet-152](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-152-deploy.prototxt) and [Resnet-101](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-152-deploy.prototxt) are different from [Resnet-50](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt), if you use the pre-trained weights from Kaiming's Resnet-152/101 model, you need to modify the `resnet_generator.py` script accordingly.

**Comment by peternara** [comment]
oh~ thank very much~!! i success!!!

**Comment by CrossLee1** [comment]
@peternara 
Hi, do you succeed in the training of resnet152+py_faster_rcnn?
I met the same error with you, how do you solve it?

**Comment by GBJim** [comment]
@peternara 
Do you mind to share your ResNet-152 generator and prototxt with us?
